/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ChangeLanguage: typeof import('./src/components/ChangeLanguage.vue')['default']
    DateContent: typeof import('./src/components/DateContent.vue')['default']
    FullScreen: typeof import('./src/components/FullScreen.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    NavbarThemeSwitcher: typeof import('./src/components/NavbarThemeSwitcher.vue')['default']
    NavItems: typeof import('./src/components/NavItems.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    Topbar: typeof import('./src/components/Topbar.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
